package com.worldcup.tactics.data.mapper

import com.worldcup.tactics.domain.model.Player

/**
 * Maps a row from the compact players.csv (generated by scripts/merge_players.py)
 * to the domain [Player] model.
 *
 * CSV column layout (9 columns):
 *   0  player_id      — numeric ID from source dataset
 *   1  player_name    — full name (cleaned, no duplicated words)
 *   2  team           — canonical national team name (matches TeamIdMapper)
 *   3  jersey_number  — assigned 1-26 within each 26-player squad
 *   4  position       — Goalkeeper | Defender | Midfielder | Forward
 *   5  nationality    — same as team for national-team players
 *   6  height_cm      — integer centimetres, may be blank
 *   7  weight_kg      — integer kilograms, may be blank
 *   8  club_name      — club name (may contain commas escaped by CSV quoting)
 */
object CsvPlayerMapper {

    fun toDomain(columns: List<String>): Player {

        val id = columns[0]
            .toIntOrNull()
            ?: columns[1].hashCode()

        return Player(
            id = -id, // Negative IDs prevent collisions with SportsDB IDs
            name = columns[1].trim(),
            number = columns[3].toIntOrNull(),
            position = normalisePosition(columns[4]),
            nationality = columns[5].trim(),
            photoUrl = null,
            clubName = columns[8].trim().ifBlank { null },
            height = columns[6]
                .trim()
                .takeIf { it.isNotBlank() }
                ?.let { "$it cm" },
            weight = columns[7]
                .trim()
                .takeIf { it.isNotBlank() }
                ?.let { "$it kg" }
        )
    }

    private fun normalisePosition(position: String): String =
        when (position.trim().lowercase()) {

            "goalkeeper", "gk" -> "Goalkeeper"

            "defender", "def",
            "centre-back", "center-back",
            "left-back", "right-back",
            "full-back", "wing-back" -> "Defender"

            "midfielder", "mid",
            "central midfielder", "defensive midfielder",
            "attacking midfielder", "left midfielder",
            "right midfielder" -> "Midfielder"

            "forward", "fwd",
            "striker", "winger",
            "centre-forward", "center-forward" -> "Forward"

            else -> position
        }
}